// Types for `onnxruntime-node`.
//
// WHY THIS FILE EXISTS. onnxruntime-node@1.20.1 ships its JS but NOT its `.d.ts` files: the
// declarations are generated by the package's own `prepare` script, and npm never runs
// `prepare` for a package installed from a registry tarball (the same npm behaviour `.npmrc`'s
// `ignore-scripts=true` note documents from the other direction). Newer 1.22+ tarballs do
// include them, but this project pins 1.20.1 deliberately — it is the version whose
// `postinstall` is a verified hard no-op on Windows and whose `bin/napi-v3` layout the
// electron-builder excludes are written against.
//
// WHY IT IS SOUND rather than a `declare module ... any` silencer. `onnxruntime-node`'s entry
// point re-exports `onnxruntime-common` verbatim and additionally registers the native backend
// as a side effect — that is the whole module. `onnxruntime-common` DOES ship complete
// declarations, so mapping one to the other gives the real `InferenceSession` and `Tensor`
// types (which is how `worker.ts`'s feeds are type-checked at all), and any drift in the
// upstream API surface shows up here as a type error instead of being erased to `any`.

declare module 'onnxruntime-node' {
  export * from 'onnxruntime-common'
}
