// sounds.ts — sound-pack discovery + audio bytes over IPC (Task #18).
//
// A pack = a directory containing `manifest.json`:
//   { id, name, sounds: { [soundId]: { file, label } }, license? }
// (an optional `license` string is copied verbatim from an imported pack's source
//  manifest — e.g. the CC-BY-NC-4.0 of the peon/marine PeonPing packs.)
// Two sources:
//   (1) bundled  — the shipped `resources/soundpacks/*` (the default pack lives
//       here; generated by scripts/gen-sounds.mts). asarUnpack in
//       electron-builder.yml keeps these on disk in production.
//   (2) user     — `<userData>/soundpacks/<id>/`, so a user can drop their own
//       audio (e.g. their real FF fanfare mp3) + a manifest and select it.
//
// getSoundData reads the referenced file and returns { mime, dataBase64 } so the
// CSP-restricted renderer can build a Blob URL (no file:// or remote fetch).

import { app } from 'electron'
import { existsSync, readdirSync, readFileSync, statSync } from 'node:fs'
import { join } from 'node:path'
import { logError } from './errorLog'
import type { SoundData, SoundPack, SoundPackManifest } from '../shared/types'

const AUDIO_MIME: Record<string, string> = {
  '.wav': 'audio/wav',
  '.mp3': 'audio/mpeg',
  '.ogg': 'audio/ogg'
}

/** Bundled soundpacks root. In dev `app.getAppPath()` is the project root (where
 *  `resources/` lives); in a packaged app the folder is unpacked next to the asar
 *  under `process.resourcesPath`. Try both. */
function bundledRoots(): string[] {
  const roots = [
    join(app.getAppPath(), 'resources', 'soundpacks'),
    join(process.resourcesPath ?? '', 'soundpacks'),
    // packaged: resources are asarUnpack'd under app.asar.unpacked/resources
    join(app.getAppPath() + '.unpacked', 'resources', 'soundpacks')
  ]
  return roots.filter((r) => r && existsSync(r))
}

/** User soundpacks root: `<userData>/soundpacks`. Created lazily on demand. */
function userRoot(): string {
  return join(app.getPath('userData'), 'soundpacks')
}

/** Read + validate a pack manifest from a directory; null if missing/invalid. */
function readManifest(dir: string): SoundPackManifest | null {
  const manifestPath = join(dir, 'manifest.json')
  if (!existsSync(manifestPath)) return null
  try {
    const parsed = JSON.parse(readFileSync(manifestPath, 'utf8')) as SoundPackManifest
    if (!parsed || typeof parsed.id !== 'string' || typeof parsed.sounds !== 'object') return null
    return parsed
  } catch (err) {
    logError('main:sounds', { message: `bad manifest at ${manifestPath}`, err })
    return null
  }
}

/** Enumerate pack directories under a root that contain a valid manifest. */
function packsInRoot(root: string, source: SoundPack['source']): SoundPack[] {
  if (!existsSync(root)) return []
  const out: SoundPack[] = []
  let entries: string[] = []
  try {
    entries = readdirSync(root)
  } catch {
    return []
  }
  for (const name of entries) {
    const dir = join(root, name)
    try {
      if (!statSync(dir).isDirectory()) continue
    } catch {
      continue
    }
    const manifest = readManifest(dir)
    if (manifest) out.push({ ...manifest, source })
  }
  return out
}

/**
 * Locate the on-disk directory for a pack id across bundled + user roots. User
 * packs shadow bundled ones with the same id (so a user can override 'default').
 */
function packDir(packId: string): { dir: string; source: SoundPack['source'] } | null {
  const uDir = join(userRoot(), packId)
  if (existsSync(join(uDir, 'manifest.json'))) return { dir: uDir, source: 'user' }
  for (const root of bundledRoots()) {
    const bDir = join(root, packId)
    if (existsSync(join(bDir, 'manifest.json'))) return { dir: bDir, source: 'bundled' }
  }
  return null
}

/** List all packs (bundled first, then user), de-duped by id (user wins). */
export function listPacks(): SoundPack[] {
  const byId = new Map<string, SoundPack>()
  for (const root of bundledRoots()) {
    for (const p of packsInRoot(root, 'bundled')) if (!byId.has(p.id)) byId.set(p.id, p)
  }
  for (const p of packsInRoot(userRoot(), 'user')) byId.set(p.id, p) // user overrides bundled
  return [...byId.values()]
}

/** Read a sound's bytes → { mime, dataBase64 }. Null if the pack/sound/file is missing. */
export function getSoundData(packId: string, soundId: string): SoundData | null {
  const loc = packDir(packId)
  if (!loc) return null
  const manifest = readManifest(loc.dir)
  const sound = manifest?.sounds?.[soundId]
  if (!sound) return null
  const file = join(loc.dir, sound.file)
  // Guard against manifest paths escaping the pack dir.
  if (!file.startsWith(loc.dir)) return null
  if (!existsSync(file)) return null
  const ext = sound.file.slice(sound.file.lastIndexOf('.')).toLowerCase()
  const mime = AUDIO_MIME[ext]
  if (!mime) return null
  try {
    const buf = readFileSync(file)
    return { mime, dataBase64: buf.toString('base64') }
  } catch (err) {
    logError('main:sounds', { message: `failed reading ${file}`, err })
    return null
  }
}
